spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://1authority-interns.1rivet.com:5004
          jwkSeturi: https://1authority-interns.1rivet.com:5004/.well-known/openid-configuration/jwks
          audiences: DeskBookApi
          
          